import { describe, it, expect } from 'bun:test';
import { verifyPassword } from '@/lib/auth/password';
import { DEMO_ACCOUNT_PASSWORDS, DEMO_PASSWORD } from '@/lib/demo-constants';
import {
  DEMO_DEFAULT_PASSWORD_HASH,
  DEMO_PASSWORD_HASHES,
  demoPasswordHashFor,
} from '@/lib/demo-password-hashes';

// These baked hashes are generated by scripts/gen-demo-hashes.ts. If a demo
// password changes without re-running the generator, the printed login note
// would no longer match the seeded hash. This test catches that drift — re-run
// `bun run scripts/gen-demo-hashes.ts` if it fails.
describe('demo password hashes (precomputed)', () => {
  it('has a baked hash for every account password', () => {
    expect(Object.keys(DEMO_PASSWORD_HASHES).sort()).toEqual(
      Object.keys(DEMO_ACCOUNT_PASSWORDS).sort(),
    );
  });

  for (const [email, password] of Object.entries(DEMO_ACCOUNT_PASSWORDS)) {
    it(`baked hash verifies for ${email}`, async () => {
      expect(await verifyPassword(DEMO_PASSWORD_HASHES[email]!, password)).toBe(true);
    });
  }

  it('fallback hash verifies for the generic demo password', async () => {
    expect(await verifyPassword(DEMO_DEFAULT_PASSWORD_HASH, DEMO_PASSWORD)).toBe(true);
  });

  it('demoPasswordHashFor falls back for an unknown email', () => {
    expect(demoPasswordHashFor('nobody@example.com')).toBe(DEMO_DEFAULT_PASSWORD_HASH);
  });
});
